name: Deploy Alexa Model

on:
  push:
    branches: [ "main" ]
    # Veröffentlicht Tags als vX.Y.Z
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Docker Build & Publish" ]
    types:
      - completed

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      alexa: ${{ steps.filter.outputs.alexa }} # Ergebnis exportieren
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            alexa: 'alexa_model.json'

  # ----------------------------------------------------------------
  # JOB 2: Alexa Interaction Model Deployen
  # ----------------------------------------------------------------
  deploy-alexa-model:
    name: Deploy Alexa JSON
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 1. Prüfen, was sich geändert hat
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            alexa:
              - 'alexa_model.json'

      # Wir brauchen Node.js für die ASK CLI
      - name: Deploy Alexa Model
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install ASK CLInp
        run: |
          npm install
          npx ask --version

      # Hier nutzen wir die Secrets, um die Config on-the-fly zu bauen
      - name: Configure ASK CLI
        env:
          ASK_REFRESH_TOKEN: ${{ secrets.ASK_REFRESH_TOKEN }}
          ASK_CLIENT_ID: ${{ secrets.ASK_CLIENT_ID }}
          ASK_CLIENT_SECRET: ${{ secrets.ASK_CLIENT_SECRET }}
          $ALEXA_VENDOR_ID: ${{ secrets.ALEXA_VENDOR_ID }}

        run: |
          mkdir -p ~/.ask
          
          # Wir nutzen jq, um das JSON sicher zu bauen
          jq -n \
          --arg rt "$ASK_REFRESH_TOKEN" \
          --arg cid "$ASK_CLIENT_ID" \
          --arg cs "$ASK_CLIENT_SECRET" \
          --arg vid "$ALEXA_VENDOR_ID" \
          '{
           profiles: {
             default: {
               token: {
                 access_token: "UNUSED",
                 refresh_token: $rt,
                 token_type: "bearer",
                 expires_in: 3600,
                 expires_at: 0
               },
               aws_profile: "__ua__",
               alexa_developer_client_id: $cid,
               alexa_developer_client_secret: $cs,
               vendor_id: $vid
             }
           }
          }' > ~/.ask/cli_config

      - name: Deploy Model via SMAPI
        env:
          SKILL_ID: ${{ secrets.ALEXA_SKILL_ID }}
        run: |
          echo "Deploying Interaction Model for Skill $SKILL_ID..."
          npx ask smapi set-interaction-model \
            -s $SKILL_ID \
            -g development \
            -l de-DE \
            --interaction-model "file:./alexa_model.json"
            --debug

      - name: Check Build Status (Optional)
        env:
          SKILL_ID: ${{ secrets.ALEXA_SKILL_ID }}
        run: |
          # Fragt den Status ab, um zu sehen, ob das Modell valide war
          npx ask smapi get-skill-status --skill-id $SKILL_ID --resource manifest
